name: Deploy to weboldalam-dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Repo klónozása (dev branch)
      uses: actions/checkout@v3
      with:
        ref: dev

    - name: weboldalam-dev repo klónozása
      run: |
        git clone https://x-access-token:${{ secrets.ACTIONS_DEPLOY_KEY }}@github.com/tanczikm/weboldalam-dev.git weboldalam-dev

    - name: Tartalom másolása a dev repóba
      run: |
        rsync -av --delete --exclude='.git' ./ weboldalam-dev/

    - name: Commit és push a dev repóba
      run: |
        cd weboldalam-dev
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add .
        git commit -m "Automatikus deploy a dev branche-ből" || echo "Nincs változás"
        git push origin main
